寡妇立希
changeFigure:改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/后发/model.json -id=model %me%;\nchangeFigure:改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/身体/025_live_event_243_rmodel.json -id=model %me%;\nchangeFigure:改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/头/model.json -id=model %me%;\nchangeFigure:改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/帽子/025_live_event_243_rmodel.json -id=model %me%;
改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/后发/model.json
setTransform:%me% -target=model -duration=750;\nsetTransform:%me% -target=model -duration=750;\nsetTransform:%me% -target=model -duration=750;\nsetTransform:%me% -target=model -duration=750;
0.000|0.000|1.000|0.000
改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/身体/025_live_event_243_rmodel.json\n改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/头/model.json\n改模/拼好模/寡妇立希/game/figure/改模/拼好模/寡妇立希/帽子/025_live_event_243_rmodel.json
0,0,0,0,0,0
0